function [ys_, params, info] = rbc_nonlinear_stoch2_steadystate2(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    ys_(10)=1;
    ys_(5)=exp(exo_(1)/(1-params(8)));
    ys_(9)=1;
    ys_(6)=1/params(1)+params(2)-1;
    K_L=(ys_(5)*ys_(9)*params(7)/ys_(6))^(1/(1-params(7)));
    ys_(7)=ys_(5)*ys_(9)*(1-params(7))*K_L^params(7);
    IV_L=params(2)*K_L;
    Y_L=ys_(5)*K_L^params(7);
    C_L=Y_L-IV_L;
    L0=0.3333333333333333;
    ys_(4)=rbc_steady_state_helper(L0,ys_(7),C_L,params(5),params(6),params(4),params(3));
    ys_(2)=C_L*ys_(4);
    ys_(1)=Y_L*ys_(4);
    ys_(8)=IV_L*ys_(4);
    ys_(3)=K_L*ys_(4);
    ys_(11)=params(7)*Y_L/K_L;
    ys_(12)=(1-params(7))*Y_L;
    % Auxiliary equations
    check_=0;
end
