%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

clearvars -global
clear_persistent_variables(fileparts(which('dynare')), false)
tic0 = tic;
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info
options_ = [];
M_.fname = 'basicNKMtidy';
M_.dynare_version = '6.1';
oo_.dynare_version = '6.1';
options_.dynare_version = '6.1';
%
% Some global variables initialization
%
global_initialization;
M_.exo_names = cell(3,1);
M_.exo_names_tex = cell(3,1);
M_.exo_names_long = cell(3,1);
M_.exo_names(1) = {'epsilon_z'};
M_.exo_names_tex(1) = {'epsilon\_z'};
M_.exo_names_long(1) = {'epsilon_z'};
M_.exo_names(2) = {'epsilon_p'};
M_.exo_names_tex(2) = {'epsilon\_p'};
M_.exo_names_long(2) = {'epsilon_p'};
M_.exo_names(3) = {'epsilon_i'};
M_.exo_names_tex(3) = {'epsilon\_i'};
M_.exo_names_long(3) = {'epsilon_i'};
M_.endo_names = cell(17,1);
M_.endo_names_tex = cell(17,1);
M_.endo_names_long = cell(17,1);
M_.endo_names(1) = {'y'};
M_.endo_names_tex(1) = {'y'};
M_.endo_names_long(1) = {'y'};
M_.endo_names(2) = {'c'};
M_.endo_names_tex(2) = {'c'};
M_.endo_names_long(2) = {'c'};
M_.endo_names(3) = {'m'};
M_.endo_names_tex(3) = {'m'};
M_.endo_names_long(3) = {'m'};
M_.endo_names(4) = {'r'};
M_.endo_names_tex(4) = {'r'};
M_.endo_names_long(4) = {'r'};
M_.endo_names(5) = {'int'};
M_.endo_names_tex(5) = {'int'};
M_.endo_names_long(5) = {'int'};
M_.endo_names(6) = {'pii'};
M_.endo_names_tex(6) = {'pii'};
M_.endo_names_long(6) = {'pii'};
M_.endo_names(7) = {'mc'};
M_.endo_names_tex(7) = {'mc'};
M_.endo_names_long(7) = {'mc'};
M_.endo_names(8) = {'x'};
M_.endo_names_tex(8) = {'x'};
M_.endo_names_long(8) = {'x'};
M_.endo_names(9) = {'xi_z'};
M_.endo_names_tex(9) = {'xi\_z'};
M_.endo_names_long(9) = {'xi_z'};
M_.endo_names(10) = {'xi_p'};
M_.endo_names_tex(10) = {'xi\_p'};
M_.endo_names_long(10) = {'xi_p'};
M_.endo_names(11) = {'xi_i'};
M_.endo_names_tex(11) = {'xi\_i'};
M_.endo_names_long(11) = {'xi_i'};
M_.endo_names(12) = {'p'};
M_.endo_names_tex(12) = {'p'};
M_.endo_names_long(12) = {'p'};
M_.endo_names(13) = {'yn'};
M_.endo_names_tex(13) = {'yn'};
M_.endo_names_long(13) = {'yn'};
M_.endo_names(14) = {'cn'};
M_.endo_names_tex(14) = {'cn'};
M_.endo_names_long(14) = {'cn'};
M_.endo_names(15) = {'rn'};
M_.endo_names_tex(15) = {'rn'};
M_.endo_names_long(15) = {'rn'};
M_.endo_names(16) = {'ygap'};
M_.endo_names_tex(16) = {'ygap'};
M_.endo_names_long(16) = {'ygap'};
M_.endo_names(17) = {'mreal'};
M_.endo_names_tex(17) = {'mreal'};
M_.endo_names_long(17) = {'mreal'};
M_.endo_partitions = struct();
M_.param_names = cell(18,1);
M_.param_names_tex = cell(18,1);
M_.param_names_long = cell(18,1);
M_.param_names(1) = {'betta'};
M_.param_names_tex(1) = {'betta'};
M_.param_names_long(1) = {'betta'};
M_.param_names(2) = {'delta'};
M_.param_names_tex(2) = {'delta'};
M_.param_names_long(2) = {'delta'};
M_.param_names(3) = {'eta_c'};
M_.param_names_tex(3) = {'eta\_c'};
M_.param_names_long(3) = {'eta_c'};
M_.param_names(4) = {'eta_m'};
M_.param_names_tex(4) = {'eta\_m'};
M_.param_names_long(4) = {'eta_m'};
M_.param_names(5) = {'eta_n'};
M_.param_names_tex(5) = {'eta\_n'};
M_.param_names_long(5) = {'eta_n'};
M_.param_names(6) = {'theta_p'};
M_.param_names_tex(6) = {'theta\_p'};
M_.param_names_long(6) = {'theta_p'};
M_.param_names(7) = {'kappa_pii'};
M_.param_names_tex(7) = {'kappa\_pii'};
M_.param_names_long(7) = {'kappa_pii'};
M_.param_names(8) = {'kappa_y'};
M_.param_names_tex(8) = {'kappa\_y'};
M_.param_names_long(8) = {'kappa_y'};
M_.param_names(9) = {'rho_z'};
M_.param_names_tex(9) = {'rho\_z'};
M_.param_names_long(9) = {'rho_z'};
M_.param_names(10) = {'rho_p'};
M_.param_names_tex(10) = {'rho\_p'};
M_.param_names_long(10) = {'rho_p'};
M_.param_names(11) = {'rho_i'};
M_.param_names_tex(11) = {'rho\_i'};
M_.param_names_long(11) = {'rho_i'};
M_.param_names(12) = {'rho_iexo'};
M_.param_names_tex(12) = {'rho\_iexo'};
M_.param_names_long(12) = {'rho_iexo'};
M_.param_names(13) = {'rho_mu'};
M_.param_names_tex(13) = {'rho\_mu'};
M_.param_names_long(13) = {'rho_mu'};
M_.param_names(14) = {'phi_z'};
M_.param_names_tex(14) = {'phi\_z'};
M_.param_names_long(14) = {'phi_z'};
M_.param_names(15) = {'sigmaz'};
M_.param_names_tex(15) = {'sigmaz'};
M_.param_names_long(15) = {'sigmaz'};
M_.param_names(16) = {'sigmap'};
M_.param_names_tex(16) = {'sigmap'};
M_.param_names_long(16) = {'sigmap'};
M_.param_names(17) = {'sigmai'};
M_.param_names_tex(17) = {'sigmai'};
M_.param_names_long(17) = {'sigmai'};
M_.param_names(18) = {'sigmamu'};
M_.param_names_tex(18) = {'sigmamu'};
M_.param_names_long(18) = {'sigmamu'};
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 3;
M_.endo_nbr = 17;
M_.param_nbr = 18;
M_.orig_endo_nbr = 17;
M_.aux_vars = [];
M_.Sigma_e = zeros(3, 3);
M_.Correlation_matrix = eye(3, 3);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = true;
M_.det_shocks = [];
M_.surprise_shocks = [];
M_.learnt_shocks = [];
M_.learnt_endval = [];
M_.heteroskedastic_shocks.Qvalue_orig = [];
M_.heteroskedastic_shocks.Qscale_orig = [];
M_.matched_irfs = {};
M_.matched_irfs_weights = {};
options_.linear = true;
options_.block = false;
options_.bytecode = false;
options_.use_dll = false;
options_.ramsey_policy = false;
options_.discretionary_policy = false;
M_.nonzero_hessian_eqs = [];
M_.hessian_eq_zero = isempty(M_.nonzero_hessian_eqs);
M_.eq_nbr = 17;
M_.ramsey_orig_eq_nbr = 0;
M_.ramsey_orig_endo_nbr = 0;
M_.set_auxiliary_variables = exist(['./+' M_.fname '/set_auxiliary_variables.m'], 'file') == 2;
M_.epilogue_names = {};
M_.epilogue_var_list_ = {};
M_.orig_maximum_endo_lag = 1;
M_.orig_maximum_endo_lead = 1;
M_.orig_maximum_exo_lag = 0;
M_.orig_maximum_exo_lead = 0;
M_.orig_maximum_exo_det_lag = 0;
M_.orig_maximum_exo_det_lead = 0;
M_.orig_maximum_lag = 1;
M_.orig_maximum_lead = 1;
M_.orig_maximum_lag_with_diffs_expanded = 1;
M_.lead_lag_incidence = [
 0 6 0;
 0 7 23;
 0 8 0;
 0 9 0;
 1 10 0;
 0 11 24;
 0 12 0;
 0 13 0;
 2 14 0;
 3 15 0;
 4 16 0;
 5 17 0;
 0 18 0;
 0 19 25;
 0 20 0;
 0 21 0;
 0 22 0;]';
M_.nstatic = 9;
M_.nfwrd   = 3;
M_.npred   = 5;
M_.nboth   = 0;
M_.nsfwrd   = 3;
M_.nspred   = 5;
M_.ndynamic   = 8;
M_.dynamic_tmp_nbr = [1; 0; 0; 0; ];
M_.equations_tags = {
  1 , 'name' , 'y' ;
  2 , 'name' , 'c' ;
  3 , 'name' , '3' ;
  4 , 'name' , 'pii' ;
  5 , 'name' , 'int' ;
  6 , 'name' , '6' ;
  7 , 'name' , 'mc' ;
  8 , 'name' , 'x' ;
  9 , 'name' , '9' ;
  10 , 'name' , 'xi_z' ;
  11 , 'name' , 'xi_p' ;
  12 , 'name' , 'xi_i' ;
  13 , 'name' , 'yn' ;
  14 , 'name' , '14' ;
  15 , 'name' , 'cn' ;
  16 , 'name' , 'ygap' ;
  17 , 'name' , 'mreal' ;
};
M_.mapping.y.eqidx = [1 7 16 ];
M_.mapping.c.eqidx = [1 2 3 ];
M_.mapping.m.eqidx = [3 17 ];
M_.mapping.r.eqidx = [2 5 ];
M_.mapping.int.eqidx = [3 5 9 ];
M_.mapping.pii.eqidx = [4 5 6 9 ];
M_.mapping.mc.eqidx = [6 7 8 ];
M_.mapping.x.eqidx = [8 ];
M_.mapping.xi_z.eqidx = [7 10 14 ];
M_.mapping.xi_p.eqidx = [6 11 ];
M_.mapping.xi_i.eqidx = [9 12 ];
M_.mapping.p.eqidx = [3 4 17 ];
M_.mapping.yn.eqidx = [13 14 16 ];
M_.mapping.cn.eqidx = [13 15 ];
M_.mapping.rn.eqidx = [15 ];
M_.mapping.ygap.eqidx = [9 16 ];
M_.mapping.mreal.eqidx = [17 ];
M_.mapping.epsilon_z.eqidx = [10 ];
M_.mapping.epsilon_p.eqidx = [11 ];
M_.mapping.epsilon_i.eqidx = [12 ];
M_.static_and_dynamic_models_differ = false;
M_.has_external_function = false;
M_.block_structure.time_recursive = false;
M_.block_structure.block(1).Simulation_Type = 1;
M_.block_structure.block(1).endo_nbr = 3;
M_.block_structure.block(1).mfs = 3;
M_.block_structure.block(1).equation = [ 10 11 12];
M_.block_structure.block(1).variable = [ 9 10 11];
M_.block_structure.block(1).is_linear = true;
M_.block_structure.block(1).NNZDerivatives = 6;
M_.block_structure.block(1).bytecode_jacob_cols_to_sparse = [1 2 3 4 5 6 ];
M_.block_structure.block(2).Simulation_Type = 3;
M_.block_structure.block(2).endo_nbr = 1;
M_.block_structure.block(2).mfs = 1;
M_.block_structure.block(2).equation = [ 14];
M_.block_structure.block(2).variable = [ 13];
M_.block_structure.block(2).is_linear = true;
M_.block_structure.block(2).NNZDerivatives = 1;
M_.block_structure.block(2).bytecode_jacob_cols_to_sparse = [1 ];
M_.block_structure.block(3).Simulation_Type = 3;
M_.block_structure.block(3).endo_nbr = 1;
M_.block_structure.block(3).mfs = 1;
M_.block_structure.block(3).equation = [ 13];
M_.block_structure.block(3).variable = [ 14];
M_.block_structure.block(3).is_linear = true;
M_.block_structure.block(3).NNZDerivatives = 1;
M_.block_structure.block(3).bytecode_jacob_cols_to_sparse = [1 ];
M_.block_structure.block(4).Simulation_Type = 3;
M_.block_structure.block(4).endo_nbr = 1;
M_.block_structure.block(4).mfs = 1;
M_.block_structure.block(4).equation = [ 15];
M_.block_structure.block(4).variable = [ 15];
M_.block_structure.block(4).is_linear = true;
M_.block_structure.block(4).NNZDerivatives = 1;
M_.block_structure.block(4).bytecode_jacob_cols_to_sparse = [1 ];
M_.block_structure.block(5).Simulation_Type = 8;
M_.block_structure.block(5).endo_nbr = 7;
M_.block_structure.block(5).mfs = 4;
M_.block_structure.block(5).equation = [ 1 7 16 5 9 2 6];
M_.block_structure.block(5).variable = [ 1 7 16 4 5 2 6];
M_.block_structure.block(5).is_linear = true;
M_.block_structure.block(5).NNZDerivatives = 15;
M_.block_structure.block(5).bytecode_jacob_cols_to_sparse = [2 0 0 0 5 6 7 8 11 12 ];
M_.block_structure.block(6).Simulation_Type = 3;
M_.block_structure.block(6).endo_nbr = 1;
M_.block_structure.block(6).mfs = 1;
M_.block_structure.block(6).equation = [ 4];
M_.block_structure.block(6).variable = [ 12];
M_.block_structure.block(6).is_linear = true;
M_.block_structure.block(6).NNZDerivatives = 2;
M_.block_structure.block(6).bytecode_jacob_cols_to_sparse = [0 1 ];
M_.block_structure.block(7).Simulation_Type = 3;
M_.block_structure.block(7).endo_nbr = 1;
M_.block_structure.block(7).mfs = 1;
M_.block_structure.block(7).equation = [ 3];
M_.block_structure.block(7).variable = [ 3];
M_.block_structure.block(7).is_linear = true;
M_.block_structure.block(7).NNZDerivatives = 1;
M_.block_structure.block(7).bytecode_jacob_cols_to_sparse = [1 ];
M_.block_structure.block(8).Simulation_Type = 1;
M_.block_structure.block(8).endo_nbr = 2;
M_.block_structure.block(8).mfs = 2;
M_.block_structure.block(8).equation = [ 17 8];
M_.block_structure.block(8).variable = [ 17 8];
M_.block_structure.block(8).is_linear = true;
M_.block_structure.block(8).NNZDerivatives = 2;
M_.block_structure.block(8).bytecode_jacob_cols_to_sparse = [3 4 ];
M_.block_structure.block(1).g1_sparse_rowval = int32([]);
M_.block_structure.block(1).g1_sparse_colval = int32([]);
M_.block_structure.block(1).g1_sparse_colptr = int32([]);
M_.block_structure.block(2).g1_sparse_rowval = int32([1 ]);
M_.block_structure.block(2).g1_sparse_colval = int32([1 ]);
M_.block_structure.block(2).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure.block(3).g1_sparse_rowval = int32([1 ]);
M_.block_structure.block(3).g1_sparse_colval = int32([1 ]);
M_.block_structure.block(3).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure.block(4).g1_sparse_rowval = int32([1 ]);
M_.block_structure.block(4).g1_sparse_colval = int32([1 ]);
M_.block_structure.block(4).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure.block(5).g1_sparse_rowval = int32([2 1 3 1 2 2 3 4 2 4 3 1 4 ]);
M_.block_structure.block(5).g1_sparse_colval = int32([2 5 5 6 6 7 7 7 8 8 11 12 12 ]);
M_.block_structure.block(5).g1_sparse_colptr = int32([1 1 2 2 2 4 6 9 11 11 11 12 14 ]);
M_.block_structure.block(6).g1_sparse_rowval = int32([1 ]);
M_.block_structure.block(6).g1_sparse_colval = int32([1 ]);
M_.block_structure.block(6).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure.block(7).g1_sparse_rowval = int32([1 ]);
M_.block_structure.block(7).g1_sparse_colval = int32([1 ]);
M_.block_structure.block(7).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure.block(8).g1_sparse_rowval = int32([]);
M_.block_structure.block(8).g1_sparse_colval = int32([]);
M_.block_structure.block(8).g1_sparse_colptr = int32([]);
M_.block_structure.variable_reordered = [ 9 10 11 13 14 15 1 7 16 4 5 2 6 12 3 17 8];
M_.block_structure.equation_reordered = [ 10 11 12 14 13 15 1 7 16 5 9 2 6 4 3 17 8];
M_.block_structure.incidence(1).lead_lag = -1;
M_.block_structure.incidence(1).sparse_IM = [
 4 12;
 9 5;
 10 9;
 11 10;
 12 11;
];
M_.block_structure.incidence(2).lead_lag = 0;
M_.block_structure.incidence(2).sparse_IM = [
 1 1;
 1 2;
 2 2;
 2 4;
 3 2;
 3 3;
 3 5;
 3 12;
 4 6;
 4 12;
 5 4;
 5 5;
 6 6;
 6 7;
 6 10;
 7 1;
 7 7;
 7 9;
 8 7;
 8 8;
 9 5;
 9 6;
 9 11;
 9 16;
 10 9;
 11 10;
 12 11;
 13 13;
 13 14;
 14 9;
 14 13;
 15 14;
 15 15;
 16 1;
 16 13;
 16 16;
 17 3;
 17 12;
 17 17;
];
M_.block_structure.incidence(3).lead_lag = 1;
M_.block_structure.incidence(3).sparse_IM = [
 2 2;
 5 6;
 6 6;
 15 14;
];
M_.block_structure.dyn_tmp_nbr = 0;
M_.state_var = [9 10 11 5 12 ];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(17, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(3, 1);
M_.params = NaN(18, 1);
M_.endo_trends = struct('deflator', cell(17, 1), 'log_deflator', cell(17, 1), 'growth_factor', cell(17, 1), 'log_growth_factor', cell(17, 1));
M_.NNZDerivatives = [51; 0; -1; ];
M_.dynamic_g1_sparse_rowval = int32([9 10 11 12 4 1 7 16 1 2 3 3 17 2 5 3 5 9 4 6 9 6 7 8 8 7 10 14 6 11 9 12 3 4 17 13 14 16 13 15 15 9 16 17 2 5 6 15 10 11 12 ]);
M_.dynamic_g1_sparse_colval = int32([5 9 10 11 12 18 18 18 19 19 19 20 20 21 21 22 22 22 23 23 23 24 24 24 25 26 26 26 27 27 28 28 29 29 29 30 30 30 31 31 32 33 33 34 36 40 40 48 52 53 54 ]);
M_.dynamic_g1_sparse_colptr = int32([1 1 1 1 1 2 2 2 2 3 4 5 6 6 6 6 6 6 9 12 14 16 19 22 25 26 29 31 33 36 39 41 42 44 45 45 46 46 46 46 48 48 48 48 48 48 48 48 49 49 49 49 50 51 52 ]);
M_.dynamic_g2_sparse_indices = int32([]);
M_.lhs = {
'y'; 
'c'; 
'm-p'; 
'pii'; 
'int'; 
'pii'; 
'mc'; 
'x'; 
'int'; 
'xi_z'; 
'xi_p'; 
'xi_i'; 
'yn'; 
'(eta_c+eta_n)*yn'; 
'cn'; 
'ygap'; 
'mreal'; 
};
M_.static_tmp_nbr = [1; 0; 0; 0; ];
M_.static_g1_sparse_rowval = int32([1 7 16 1 3 3 17 2 5 3 5 9 4 5 6 9 6 7 8 8 7 10 14 6 11 9 12 3 17 13 14 16 13 15 9 16 17 ]);
M_.static_g1_sparse_colval = int32([1 1 1 2 2 3 3 4 4 5 5 5 6 6 6 6 7 7 7 8 9 9 9 10 10 11 11 12 12 13 13 13 14 15 16 16 17 ]);
M_.static_g1_sparse_colptr = int32([1 4 6 8 10 13 17 20 21 24 26 28 30 33 34 35 37 38 ]);
M_.params(1) = 0.989;
betta = M_.params(1);
M_.params(2) = 0.019;
delta = M_.params(2);
M_.params(3) = 2;
eta_c = M_.params(3);
M_.params(4) = 3;
eta_m = M_.params(4);
M_.params(5) = 1;
eta_n = M_.params(5);
M_.params(6) = 0.75;
theta_p = M_.params(6);
M_.params(7) = 1.5;
kappa_pii = M_.params(7);
M_.params(8) = 0.35;
kappa_y = M_.params(8);
M_.params(9) = 0.95;
rho_z = M_.params(9);
M_.params(10) = 0.75;
rho_p = M_.params(10);
M_.params(11) = 0;
rho_i = M_.params(11);
M_.params(12) = 0;
rho_iexo = M_.params(12);
M_.params(13) = 0;
rho_mu = M_.params(13);
M_.params(14) = 0;
phi_z = M_.params(14);
M_.params(15) = 0.01;
sigmaz = M_.params(15);
M_.params(16) = 0.0025;
sigmap = M_.params(16);
M_.params(17) = 0.0025;
sigmai = M_.params(17);
M_.params(18) = 0.01;
sigmamu = M_.params(18);
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = M_.params(15)^2;
M_.Sigma_e(2, 2) = M_.params(16)^2;
M_.Sigma_e(3, 3) = M_.params(17)^2;
steady;
oo_.dr.eigval = check(M_,options_,oo_);
options_.graph_format = {'fig'};
options_.irf = 40;
options_.order = 1;
var_list_ = {'y';'ygap';'mreal';'r';'int';'pii';'mc';'x';'c';'xi_z';'xi_p';'m';'p';'rn'};
[info, oo_, options_, M_] = stoch_simul(M_, options_, oo_, var_list_);


oo_.time = toc(tic0);
disp(['Total computing time : ' dynsec2hms(oo_.time) ]);
if ~exist([M_.dname filesep 'Output'],'dir')
    mkdir(M_.dname,'Output');
end
save([M_.dname filesep 'Output' filesep 'basicNKMtidy_results.mat'], 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'basicNKMtidy_results.mat'], 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'basicNKMtidy_results.mat'], 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'basicNKMtidy_results.mat'], 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'basicNKMtidy_results.mat'], 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'basicNKMtidy_results.mat'], 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'basicNKMtidy_results.mat'], 'oo_recursive_', '-append');
end
if exist('options_mom_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'basicNKMtidy_results.mat'], 'options_mom_', '-append');
end
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
