%%A = [oo_.PosteriorTheoreticalMoments.dsge.ConditionalVarianceDecomposition.Mean.y.epsil_z' , oo_.PosteriorTheoreticalMoments.dsge.ConditionalVarianceDecomposition.Mean.y.epsil_i' , oo_.PosteriorTheoreticalMoments.dsge.ConditionalVarianceDecomposition.Mean.y.epsil_ms' , oo_.PosteriorTheoreticalMoments.dsge.ConditionalVarianceDecomposition.Mean.y.epsil_md']
clear;
load('CH2020Est5907m4_results.mat');
%load('CH2020Est5907m4test_results.mat');
%load('CH2020Est0719m4test_results.mat');

VDm = [oo_.PosteriorTheoreticalMoments.dsge.ConditionalVarianceDecomposition.Mean.m.epsil_z' , ...
    oo_.PosteriorTheoreticalMoments.dsge.ConditionalVarianceDecomposition.Mean.m.epsil_i' , ...
    oo_.PosteriorTheoreticalMoments.dsge.ConditionalVarianceDecomposition.Mean.m.epsil_ms' , ...
    oo_.PosteriorTheoreticalMoments.dsge.ConditionalVarianceDecomposition.Mean.m.epsil_md'];

VDv = [oo_.PosteriorTheoreticalMoments.dsge.ConditionalVarianceDecomposition.Mean.v.epsil_z' , ...
    oo_.PosteriorTheoreticalMoments.dsge.ConditionalVarianceDecomposition.Mean.v.epsil_i' , ...
    oo_.PosteriorTheoreticalMoments.dsge.ConditionalVarianceDecomposition.Mean.v.epsil_ms' , ...
    oo_.PosteriorTheoreticalMoments.dsge.ConditionalVarianceDecomposition.Mean.v.epsil_md'];

VDp = [oo_.PosteriorTheoreticalMoments.dsge.ConditionalVarianceDecomposition.Mean.p.epsil_z' , ... 
    oo_.PosteriorTheoreticalMoments.dsge.ConditionalVarianceDecomposition.Mean.p.epsil_i' , ...
    oo_.PosteriorTheoreticalMoments.dsge.ConditionalVarianceDecomposition.Mean.p.epsil_ms' , ...
    oo_.PosteriorTheoreticalMoments.dsge.ConditionalVarianceDecomposition.Mean.p.epsil_md'];

VDy = [oo_.PosteriorTheoreticalMoments.dsge.ConditionalVarianceDecomposition.Mean.y.epsil_z' , ...
    oo_.PosteriorTheoreticalMoments.dsge.ConditionalVarianceDecomposition.Mean.y.epsil_i' , ...
    oo_.PosteriorTheoreticalMoments.dsge.ConditionalVarianceDecomposition.Mean.y.epsil_ms' , ...
    oo_.PosteriorTheoreticalMoments.dsge.ConditionalVarianceDecomposition.Mean.y.epsil_md'];

VDr = [oo_.PosteriorTheoreticalMoments.dsge.ConditionalVarianceDecomposition.Mean.r.epsil_z' , ...
    oo_.PosteriorTheoreticalMoments.dsge.ConditionalVarianceDecomposition.Mean.r.epsil_i' , ...
    oo_.PosteriorTheoreticalMoments.dsge.ConditionalVarianceDecomposition.Mean.r.epsil_ms' , ...
    oo_.PosteriorTheoreticalMoments.dsge.ConditionalVarianceDecomposition.Mean.r.epsil_md'];

VDpii = [oo_.PosteriorTheoreticalMoments.dsge.ConditionalVarianceDecomposition.Mean.pii.epsil_z' , ...
    oo_.PosteriorTheoreticalMoments.dsge.ConditionalVarianceDecomposition.Mean.pii.epsil_i' , ...
    oo_.PosteriorTheoreticalMoments.dsge.ConditionalVarianceDecomposition.Mean.pii.epsil_ms' , ... 
    oo_.PosteriorTheoreticalMoments.dsge.ConditionalVarianceDecomposition.Mean.pii.epsil_md'];

VDint = [oo_.PosteriorTheoreticalMoments.dsge.ConditionalVarianceDecomposition.Mean.int.epsil_z' , ...
    oo_.PosteriorTheoreticalMoments.dsge.ConditionalVarianceDecomposition.Mean.int.epsil_i' , ...
    oo_.PosteriorTheoreticalMoments.dsge.ConditionalVarianceDecomposition.Mean.int.epsil_ms' , ...
    oo_.PosteriorTheoreticalMoments.dsge.ConditionalVarianceDecomposition.Mean.int.epsil_md'];

VDytilde = [oo_.PosteriorTheoreticalMoments.dsge.ConditionalVarianceDecomposition.Mean.ytilde.epsil_z' , ...
    oo_.PosteriorTheoreticalMoments.dsge.ConditionalVarianceDecomposition.Mean.ytilde.epsil_i' , ...
    oo_.PosteriorTheoreticalMoments.dsge.ConditionalVarianceDecomposition.Mean.ytilde.epsil_ms' , ...
    oo_.PosteriorTheoreticalMoments.dsge.ConditionalVarianceDecomposition.Mean.ytilde.epsil_md'];

fVD = figure;
hold
subplot(3,2,1)
bar(VDm,'stacked')
subplot(3,2,2)
bar(VDv,'stacked')
subplot(3,2,3)
bar(VDpii,'stacked')
subplot(3,2,4)
bar(VDytilde,'stacked')
subplot(3,2,5)
bar(VDint,'stacked')
legend('Technology (\epsilon_z)','Interest target (\epsilon_i)','Money supply (\epsilon_{m^s})','Money demand (\epsilon_{m^d})', ...
    'Location','none','Position', [0.65 0.14 0.17 0.15]);

title(subplot(3,2,1),'Money')
title(subplot(3,2,2),'Velocity')
title(subplot(3,2,3),'Inflation')
title(subplot(3,2,4),'Output gap')
title(subplot(3,2,5),'Nominal interest rate')

hold off

